//! Testing Utilities Module
//!
//! This module contains useful structures for writing tests against this library.

use crate::pubsub::{Message, PubSubError};
use rdkafka::{
    ClientConfig,
    mocking::MockCluster,
    producer::{FutureProducer, FutureRecord},
};
use rust_env_var_lib::env_var;
use std::{
    collections::{HashMap, HashSet},
    fmt::{Debug, Formatter, Result as FmtResult},
    sync::{LazyLock, mpsc},
    thread::spawn,
    time::Duration,
};
use tokio::sync::{RwLock, mpsc as async_mpsc};

/// Global instance of [`MockKafka`] to be used by all test cases.
/// Utilizes [`LazyLock`] to only instantiate it once it has been referenced for the first time.
/// All subsequent references will see the same instance.
static MOCK_CLUSTER: LazyLock<MockKafka> = LazyLock::new(MockKafka::new);

/// [`FutureProducer`] is intended to be a one-per-host construct, shared by all parts of the application that need to produce on that host.
/// As such, we build a static map of the producers to be shared by all instances of [`KafkaPublisher`] that get requested for the same host.  
static PRODUCER_MAP: LazyLock<RwLock<HashMap<String, FutureProducer>>> =
    LazyLock::new(RwLock::default);

/// A set of values for running tests against an instance of [`MockCluster`].
///
/// ## WARNING
/// To conserve resources, this structure references a global instance of [`MockCluster`].
/// If topic names are reused between test cases, messages from one test case may become visible to another.
/// There is no guarantee of consistency on this, so do not build tests in anticipation of specific data from
/// another test being present.
///
/// Corollary: build tests on independent topics or design them to be agnostic
/// about preexisting data.
pub struct Harness;
impl Harness {
    /// Generates an instance of [`Harness`] with a reference to a global [`MockCluster`] that has been
    /// prepopulated with the specified topics.
    pub async fn with_topics(topics: Vec<String>) -> Self {
        for topic in topics {
            MOCK_CLUSTER.create_topic(topic).await;
        }
        Harness
    }

    /// Returns the comma-delimited list of addresses generated by the [`MockCluster`].
    pub fn host(&self) -> String {
        MOCK_CLUSTER.host()
    }
}

/// Implementation of the [`Publisher`] trait for Kafka connections.
pub struct KafkaPublisher {
    host: String,
    topic: String,
}
impl KafkaPublisher {
    async fn get_connection(&self) -> Result<FutureProducer, PubSubError> {
        let naive_read = PRODUCER_MAP.read().await.get(&self.host).cloned();
        match naive_read {
            Some(producer) => Ok(producer),
            None => {
                let mut lock = PRODUCER_MAP.write().await;
                match lock.get(&self.host).cloned() {
                    Some(producer) => Ok(producer),
                    None => {
                        let default = ClientConfig::new()
                            .set("bootstrap.servers", &self.host)
                            .create()?;
                        let producer = lock
                            .entry(self.host.clone())
                            .insert_entry(default)
                            .get()
                            .clone();
                        Ok(producer)
                    }
                }
            }
        }
    }

    pub fn new(host: String, topic: String) -> Self {
        Self { host, topic }
    }

    pub async fn publish(&self, message: Message) -> Result<(), PubSubError> {
        let producer = self.get_connection().await?;
        let mut record = FutureRecord::to(&self.topic).payload(&message.value);
        if let Some(key) = &message.key {
            record = record.key(key);
        }
        match producer.send(record, get_kafka_timeout_val()).await {
            Ok(_) => Ok(()),
            Err((err, _)) => Err(PubSubError::from(err)),
        }
    }
}
impl Debug for KafkaPublisher {
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        f.debug_struct("KafkaPublisher")
            .field("host", &self.host)
            .field("topic", &self.topic)
            .finish()
    }
}

/// A struct to manage the [`MockCluster`] thread across the test runs.
/// Maintains a list of the known topics to short-circuit the process of sending a new topic String across the threads.
struct MockKafka {
    host: String,
    known_topics: RwLock<HashSet<String>>,
    topic_sender: async_mpsc::Sender<String>,
}
impl MockKafka {
    fn new() -> Self {
        let (topic_sender, topic_receiver) = async_mpsc::channel(16);
        let (host_sender, host_receiver) = mpsc::sync_channel(1);

        spawn(move || {
            run_cluster(host_sender, topic_receiver);
        });

        let host = host_receiver
            .recv_timeout(Duration::from_secs(30))
            .expect("Failed to acquire host path for the mock cluster");

        MockKafka {
            host,
            known_topics: RwLock::default(),
            topic_sender,
        }
    }

    fn host(&self) -> String {
        self.host.clone()
    }

    async fn create_topic(&self, topic: String) {
        let has_topic = self.known_topics.read().await.contains(&topic);
        if !has_topic {
            let mut write_lock = self.known_topics.write().await;
            let is_missing_topic_after_acquiring_write_lock =
                !write_lock.contains(&topic);
            if is_missing_topic_after_acquiring_write_lock {
                self.topic_sender
                    .send(topic.clone())
                    .await
                    .expect("Failed to add topic to cluster");
                write_lock.insert(topic);
            }
        }
    }
}

fn get_kafka_timeout_val() -> Duration {
    let secs = env_var::get("KAFKA_CONNECTION_SECONDS").or(1);
    Duration::from_secs(secs)
}

/// The function to drive the [`MockCluster`] process.
/// Reports the host path to the [`MockKafka`] that kicks this off, then listens for requests to create new topics.
fn run_cluster(
    host_sender: mpsc::SyncSender<String>,
    mut topic_receiver: async_mpsc::Receiver<String>,
) {
    let mock_cluster = MockCluster::new(3).unwrap();

    host_sender
        .send(mock_cluster.bootstrap_servers())
        .expect("Could not send the host to the MockKafka instance");

    while let Some(topic) = topic_receiver.blocking_recv() {
        let _ = mock_cluster.create_topic(&topic, 3, 1);
    }
}
