name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    uses: fermi-ad/.github/.github/workflows/rust-integration.yaml@daa73cf39de99d47b500df80fbe6cad5abdf434b
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
    with:
      pull-git-submodules: true
